apiVersion: v1
kind: Namespace
metadata:
  name: nexus-dev
  labels:
    name: nexus-dev
    environment: development
    app.kubernetes.io/name: nexus-dev
    app.kubernetes.io/part-of: nexus-platform
