{{- if .Values.apiGateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    {{- include "nexus-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
