apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - dev.nexus.example.com
    - api.dev.nexus.example.com
    - creators.dev.nexus.example.com
    - brands.dev.nexus.example.com
    - admin.dev.nexus.example.com
    secretName: nexus-dev-tls
  rules:
  - host: api.dev.nexus.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-api-gateway
            port:
              number: 80
  - host: dev.nexus.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-web-app
            port:
              number: 80
